services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network
  
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root # Cambia esto a una contraseña segura
      MYSQL_DATABASE: EncomiendasCSM
      MYSQL_USER: csm_user
      MYSQL_PASSWORD: csm_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306" # Exponer MySQL en el puerto 3306
    networks:
      - app_network

networks:
  app_network:
